// Code generated by protoc-gen-fieldmask. DO NOT EDIT.

package ttipb

var BillingFieldPathsNested = []string{
	"provider",
	"provider.aws_saas_marketplace",
	"provider.aws_saas_marketplace.customer_identifier",
	"provider.aws_saas_marketplace.product_code",
	"provider.stripe",
	"provider.stripe.customer_id",
	"provider.stripe.plan_id",
	"provider.stripe.subscription_id",
	"provider.stripe.subscription_item_id",
}

var BillingFieldPathsTopLevel = []string{
	"provider",
}
var BillingIdentifiersFieldPathsNested = []string{
	"billing_id",
}

var BillingIdentifiersFieldPathsTopLevel = []string{
	"billing_id",
}
var Billing_StripeFieldPathsNested = []string{
	"customer_id",
	"plan_id",
	"subscription_id",
	"subscription_item_id",
}

var Billing_StripeFieldPathsTopLevel = []string{
	"customer_id",
	"plan_id",
	"subscription_id",
	"subscription_item_id",
}
var Billing_AWSSaaSMarketplaceFieldPathsNested = []string{
	"customer_identifier",
	"product_code",
}

var Billing_AWSSaaSMarketplaceFieldPathsTopLevel = []string{
	"customer_identifier",
	"product_code",
}
