// Code generated by protoc-gen-fieldmask. DO NOT EDIT.

package ttnpb

var StatusFieldPathsNested = []string{
	"code",
	"details",
	"message",
}

var StatusFieldPathsTopLevel = []string{
	"code",
	"details",
	"message",
}
